### ISSUE TITLE
How to reproduce

### ISSUE THREAD

**Issue by jihyukkim-nlp** [XinyuanWangCS/PromptAgent#17]
Hi, 

I am trying to reproduce evaluation results on BBH benchmark. 
It would be greatly appreciated if you could help reproduce the results!

(1)
**Could you share config files for other datasets in addition to Penguins?**
More precisely, I am not sure what values should be used for the `task_setting`.
```yaml
task_setting:
  train_size: ?? # This should be the same as `Train` in `Table 6: Data split`?
  eval_size: ?? 
# It seems, `A.2 DATA SPLIT` and `Table 6: Data split` in the paper are not 100% clear about this?
```

(2)
**For `object_counting`, I am wondering what the initial prompt was used.**
Was the prompt (i.e., `Count the overall number of all items.`) in `Human`, Table 12 in the paper used?

(3)
**For `penguins_in_a_table`, I am wondering what `search_setting` was used.**
It seems `example_config.yaml` uses a different `search_setting` from the default setup written in the paper.
```
search_setting:
  iteration_num: 10 # default: 12 in the paper
  expand_width: 3
  depth_limit: 5  # default: 8 in the paper
  # mcts setting
  min_depth: 2
  w_exp: 2.5
  # beam search setting
  beam_width: 3
```

Best regards,
Jihyuk Kim
